# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mer < Formula
  desc "CLI to convert currency."
  homepage "https://github.com/winebarrel/mer"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/mer/releases/download/v1.2.0/mer_1.2.0_darwin_arm64.tar.gz"
      sha256 "c2496001ae375a440ddfb2606567a61881e5f752da4b478dbb501ed752b38aed"

      def install
        bin.install 'mer'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/mer/releases/download/v1.2.0/mer_1.2.0_darwin_amd64.tar.gz"
      sha256 "89612e2f5ea353d6dcf773724b5ea2aaf3e48fb782ecbabff0acb615d2db0fa7"

      def install
        bin.install 'mer'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/mer/releases/download/v1.2.0/mer_1.2.0_linux_arm64.tar.gz"
      sha256 "279eaa1d1a353bdfc136f7c3b3115c0873bdbd0451c023270648542fba670441"

      def install
        bin.install 'mer'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/mer/releases/download/v1.2.0/mer_1.2.0_linux_amd64.tar.gz"
      sha256 "6b3ca36898895d9e7e4d60b8e775d9d8a68b64df2a5c2416d3df8abcd621a30b"

      def install
        bin.install 'mer'
      end
    end
  end
end
