# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mer < Formula
  desc "CLI to convert currency."
  homepage "https://github.com/winebarrel/mer"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/mer/releases/download/v1.0.0/mer_1.0.0_darwin_arm64.tar.gz"
      sha256 "daf90674223bd0b61de266256fb0e77442f801cd56bc44288182ea906a9cd955"

      def install
        bin.install 'mer'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/mer/releases/download/v1.0.0/mer_1.0.0_darwin_amd64.tar.gz"
      sha256 "5acc0f986d5e608d4f02341956262c46c2f48c0a16732cef6741f934cb6d179d"

      def install
        bin.install 'mer'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/mer/releases/download/v1.0.0/mer_1.0.0_linux_arm64.tar.gz"
      sha256 "842d40475d086ff6093b1cc8a903ea7f5dff8a3c7f8d16dfe7c17f92169ba8b3"

      def install
        bin.install 'mer'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/mer/releases/download/v1.0.0/mer_1.0.0_linux_amd64.tar.gz"
      sha256 "ddfca8992daccf6566789d7d0554cd6c5149128918c86f07d998cf723b7b53f3"

      def install
        bin.install 'mer'
      end
    end
  end
end
