# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mer < Formula
  desc "CLI to convert currency."
  homepage "https://github.com/winebarrel/mer"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/mer/releases/download/v1.1.0/mer_1.1.0_darwin_amd64.tar.gz"
      sha256 "d470872f78b71c5645f1015235019469c69be0b7a7596d6fa0e309da9fece04c"

      def install
        bin.install 'mer'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/mer/releases/download/v1.1.0/mer_1.1.0_darwin_arm64.tar.gz"
      sha256 "6496130eafd518bb5a9dca7cb013ee603d18edf6e120fb3e4bf918e69b206325"

      def install
        bin.install 'mer'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/mer/releases/download/v1.1.0/mer_1.1.0_linux_arm64.tar.gz"
      sha256 "de648f284fc6ca13f689a234ca823168a2890436e62ce49478f68bf1a75ca195"

      def install
        bin.install 'mer'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/mer/releases/download/v1.1.0/mer_1.1.0_linux_amd64.tar.gz"
      sha256 "77ddea54154184f694df0a51f6860c04f79fac147f7d832af2cc2b1bc2839863"

      def install
        bin.install 'mer'
      end
    end
  end
end
